"""Recommendation log model. Additive audit trail of every retention
recommendation generated by the deployed system. Does NOT alter existing tables."""
from datetime import datetime
from app.extensions import db


class RecommendationLog(db.Model):
    __tablename__ = "recommendation_log"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    customer_id = db.Column(
        db.Integer,
        db.ForeignKey("customers.customer_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    prediction_id = db.Column(
        db.Integer,
        db.ForeignKey("prediction_log.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    title = db.Column(db.String(120), nullable=False)
    action = db.Column(db.Text, nullable=True)
    severity = db.Column(db.String(20), nullable=True)
    icon = db.Column(db.String(40), nullable=True)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)

    def to_dict(self):
        return {
            "id": self.id,
            "customer_id": self.customer_id,
            "prediction_id": self.prediction_id,
            "title": self.title,
            "action": self.action,
            "severity": self.severity,
            "icon": self.icon,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        return f"<RecommendationLog #{self.id} cust={self.customer_id} '{self.title}'>"
