-- Seed all 34 provinces of Afghanistan with baseline security levels.
USE telecom_churn_db;

INSERT INTO provinces (province_name, security_level) VALUES
('Kabul', 'High'),
('Herat', 'Medium'),
('Kandahar', 'Low'),
('Balkh', 'Medium'),
('Nangarhar', 'Low'),
('Kunduz', 'Low'),
('Helmand', 'Low'),
('Ghazni', 'Low'),
('Baghlan', 'Medium'),
('Badakhshan', 'Medium'),
('Takhar', 'Medium'),
('Faryab', 'Low'),
('Jowzjan', 'Medium'),
('Samangan', 'Medium'),
('Sar-e Pol', 'Medium'),
('Bamyan', 'High'),
('Parwan', 'Medium'),
('Kapisa', 'Medium'),
('Panjshir', 'High'),
('Logar', 'Low'),
('Wardak', 'Low'),
('Paktia', 'Low'),
('Paktika', 'Low'),
('Khost', 'Low'),
('Ghor', 'Medium'),
('Daikundi', 'High'),
('Uruzgan', 'Low'),
('Zabul', 'Low'),
('Farah', 'Low'),
('Nimroz', 'Medium'),
('Badghis', 'Low'),
('Laghman', 'Low'),
('Kunar', 'Low'),
('Nuristan', 'Low')
ON DUPLICATE KEY UPDATE security_level = VALUES(security_level);
